version: "3.7"

services:
  api:
    build:
      context: .
      target: builder
    ports:
      - "9999:9999"
    volumes:
      - ./:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my_grounded
      MYSQL_DATABASE: my_grounded
      MYSQL_USER: my_grounded
      MYSQL_PASSWORD: my_grounded
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: